In [42]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [43]:
dataset = pd.read_csv("cancer patient data sets.csv")
dataset.head(3)

index Patient Id  Age  Gender  Air Pollution  Alcohol use  Dust Allergy  \
0      0         P1   33       1              2            4             5   
1      1        P10   17       1              3            1             5   
2      2       P100   35       1              4            5             6   

   OccuPational Hazards  Genetic Risk  chronic Lung Disease  ...  Fatigue  \
0                     4             3                     2  ...        3   
1                     3             4                     2  ...        1   
2                     5             5                     4  ...        8   

   Weight Loss  Shortness of Breath  Wheezing  Swallowing Difficulty  \
0            4                    2         2                      3   
1            3                    7         8                      6   
2            7                    9         2                      1   

   Clubbing of Finger Nails  Frequent Cold  Dry Cough  Snoring   Level  
0                         1              2          3        4     Low  
1                         2              1          7        2  Medium  
2                         4              6          7        2    High  

[3 rows x 26 columns]

In [6]:
#dataset = pd.read_csv("cancer patient data sets.csv")
#x=dataset.iloc[:,:-1].values
#y=dataset.iloc[:,-1].values

In [44]:
# Encode labels in multiple columns
from sklearn import preprocessing
label_encoder = preprocessing.LabelEncoder()
dataset['Level']= label_encoder.fit_transform(dataset['Level'])

In [46]:
dataset.head(3)

index Patient Id  Age  Gender  Air Pollution  Alcohol use  Dust Allergy  \
0      0         P1   33       1              2            4             5   
1      1        P10   17       1              3            1             5   
2      2       P100   35       1              4            5             6   

   OccuPational Hazards  Genetic Risk  chronic Lung Disease  ...  Fatigue  \
0                     4             3                     2  ...        3   
1                     3             4                     2  ...        1   
2                     5             5                     4  ...        8   

   Weight Loss  Shortness of Breath  Wheezing  Swallowing Difficulty  \
0            4                    2         2                      3   
1            3                    7         8                      6   
2            7                    9         2                      1   

   Clubbing of Finger Nails  Frequent Cold  Dry Cough  Snoring  Level  
0                         1              2          3        4      1  
1                         2              1          7        2      2  
2                         4              6          7        2      0  

[3 rows x 26 columns]

In [47]:
x=dataset.drop(['index','Patient Id','Level'], axis=1)
y=dataset['Level']
#x=dataset.iloc[:,:-2].values
#y=dataset.iloc[:,-1].values

In [48]:
print(x)

     Age  Gender  Air Pollution  Alcohol use  Dust Allergy  \
0     33       1              2            4             5   
1     17       1              3            1             5   
2     35       1              4            5             6   
3     37       1              7            7             7   
4     46       1              6            8             7   
..   ...     ...            ...          ...           ...   
995   44       1              6            7             7   
996   37       2              6            8             7   
997   25       2              4            5             6   
998   18       2              6            8             7   
999   47       1              6            5             6   

     OccuPational Hazards  Genetic Risk  chronic Lung Disease  Balanced Diet  \
0                       4             3                     2              2   
1                       3             4                     2              2   
2              

In [49]:
print(y)

0      1
1      2
2      0
3      0
4      0
      ..
995    0
996    0
997    0
998    0
999    0
Name: Level, Length: 1000, dtype: int32


## Split dataset into training ad test set

In [50]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train,y_test= train_test_split(x,y,test_size=0.3,random_state=0)

## Feature Sscaling

In [29]:
#from sklearn.preprocessing import StandardScaler
#sc=StandardScaler()
#x_train=sc.fit_transform(x_train)
#x_test=sc.transform(x_test)

In [51]:
print(x_train)

     Age  Gender  Air Pollution  Alcohol use  Dust Allergy  \
105   37       2              7            7             7   
68    62       1              6            8             7   
479   45       2              1            2             3   
399   45       1              3            2             4   
434   38       1              2            3             5   
..   ...     ...            ...          ...           ...   
835   44       1              2            3             2   
192   52       1              6            8             7   
629   22       1              6            8             7   
559   37       1              7            7             7   
684   36       1              6            7             7   

     OccuPational Hazards  Genetic Risk  chronic Lung Disease  Balanced Diet  \
105                     7             6                     7              7   
68                      7             7                     6              7   
479            

## Applying PCA

In [52]:
from sklearn.decomposition import PCA
pca=PCA(n_components = 2)
x_train=pca.fit_transform(x_train)
x_test=pca.fit_transform(x_test)

In [53]:
print(x_train)

[[ -0.10681696   8.30871499]
 [ 24.79965052   6.38251774]
 [  6.81018317  -6.55922348]
 ...
 [-15.13648665   2.45143719]
 [ -0.09809566   8.32495915]
 [ -0.97427582   9.82196032]]


## Training the Logistic Regression Model on the Training set

In [54]:
from sklearn.linear_model import LogisticRegression
classifier=LogisticRegression(random_state=0)
classifier.fit(x_train,y_train)

LogisticRegression(random_state=0)

In [55]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred= classifier.predict(x_test)
cm=confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test,y_pred)

[[104   0   4]
 [  4  78  17]
 [ 11  15  67]]


0.83

Accuracy for Logistic Regression after applying PCA and Standard Scaler gave a value of 10%

In [56]:
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
import sklearn.metrics as metrics

## Support Vector Machine Model

In [57]:
svm = SVC()
svm.fit(x_train, y_train)
svm.score(x_test,y_test)
y_pred = svm.predict(x_test)

In [58]:
print("Train set Accuracy: ", metrics.accuracy_score(y_train, svm.predict(x_train)))
print("Test set Accuracy: ", metrics.accuracy_score(y_test, y_pred))

Train set Accuracy:  0.8342857142857143
Test set Accuracy:  0.7633333333333333


## KNN Model

In [59]:
knn = KNeighborsClassifier()
knn.fit(x_train, y_train)
knn.score(x_test,y_test)

0.91

In [60]:
print("Train set Accuracy: ", metrics.accuracy_score(y_train, knn.predict(x_train)))
print("Test set Accuracy: ", metrics.accuracy_score(y_test, y_pred))

Train set Accuracy:  0.9942857142857143
Test set Accuracy:  0.7633333333333333


## Gaussian Naive Bayes

In [61]:
gnb = GaussianNB()
gnb.fit(x_train, y_train)
gnb.score(x_test,y_test)

0.7166666666666667

In [62]:
print("Train set Accuracy: ", metrics.accuracy_score(y_train, gnb.predict(x_train)))
print("Test set Accuracy: ", metrics.accuracy_score(y_test, y_pred))

Train set Accuracy:  0.7442857142857143
Test set Accuracy:  0.7633333333333333


## Attempt for Accuracy without applying PCA on LogisticRegression

In [57]:
#from sklearn.decomposition import PCA
#pca=PCA(n_components = 2)
#x_train1=pca.fit_transform(x_train1)
#x_test1=pca.fit_transform(x_test1)

In [58]:
from sklearn.linear_model import LogisticRegression
classifier=LogisticRegression(random_state=0)
classifier.fit(x_train1,y_train)

LogisticRegression(random_state=0)

In [59]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred= classifier.predict(x_test1)
cm=confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test,y_pred)

[[ 0  1 13]
 [ 4 11  1]
 [ 6  0  0]]


0.3055555555555556

Accuracy remained the same without PCA application

## Final comment:
Of the models considered, KNN gave the highest accuracy